services:
  api:
    image: bolao-api-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bolao-api
    restart: always
    ports:
      - "9077:8080"
    environment:
      #Host=database
      - ConnectionStrings__banco=Host=database;Port=5432;Database=BolaoIo;Username=postgres;Password=ufra123;Include Error Detail=true
      - JwtSettings__SecretKey=347terj73vg8ojesgla3akt4uweorgnijo8evgukpladut47cir7wgiagvmziou!
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database 
  database:
    image: postgres:17
    container_name: bolao-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ufra123
      - POSTGRES_DB=BolaoIo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: